name: Download METAR Data

on:
  schedule:
    # 每分钟的第0秒执行，确保整点分钟执行
    - cron: '0 * * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  download-and-store:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Download and process METAR data
      run: python3 scripts/download_metar.py
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push changes
      run: |
        git add data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add METAR data for $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
        fi
